name: Release

"on":
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
      index:
        required: true
        type: choice
        options:
          - testpypi
          - pypi

permissions:
  contents: read

jobs:
  release:
    uses: alexisbeaulieu97/untaped/.github/workflows/pypi-package-release.yml@45cef5c2c4e2f9057135480f20e183df46d94b99
    with:
      version: ${{ inputs.version }}
      index: ${{ inputs.index }}
      package: untaped-github
      console-script: untaped-github
      release-tool-ref: 45cef5c2c4e2f9057135480f20e183df46d94b99
    permissions:
      contents: write
      id-token: write
